@echo off
cd /d "E:\Glitch AI\glitch-ai"
echo Launching new Glitch session in new window...
start "" powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Normal -File "scripts\launch-free.ps1"
echo New session launched. Waiting 5s before killing old session...
timeout /t 5 /nobreak >nul
echo Finding and killing old opencode...
for /f "tokens=2" %%a in ('tasklist /fi "imagename eq opencode.exe" /nh') do set OLD_PID=%%a
if defined OLD_PID (
  echo Killing opencode (PID %OLD_PID%)...
  taskkill /f /pid %OLD_PID% >nul 2>&1
)
echo Done. Old session killed.